import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import { Toaster } from "react-hot-toast";
import NavManue from "@/shared/NavManue";
import { SessionProvider } from "next-auth/react";
import Providers from "./provider";
import AuthanticationProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta property="fb:app_id" content="380900851328722" />
      </head>
      <body className={inter.className}>
        <AuthanticationProvider>
          <div className=" z-30">
            <Navbar />
            <NavManue />
          </div>
          {children}
          <Toaster
            position="top-center"
            containerClassName="text-xs"
            reverseOrder={false}
          />
        </AuthanticationProvider>
      </body>
    </html>
  );
}
